version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/snebel29/prometheus-gcp-ssl-exporter
    steps:
      - checkout

      - run: make test
      - run: make build
      - run: make container
